version: "3.5"
services:
  ros_fastdds_discovery_server:
    image: spot_ros2:arm64
    network_mode: host
    ipc: host
    restart: unless-stopped
    # Launch the FastDDS discovery sever to bypass the need of multicast to discover nodes
    command: fastdds discovery -i 0 -p 21000
  spot_ros2:
    image: spot_ros2:arm64
    network_mode: host
    ipc: host
    restart: unless-stopped
    volumes:
      # Mount payload credentials.
      - /opt/payload_credentials/payload_guid_and_secret:/opt/payload_credentials/payload_guid_and_secret
    environment:
      - SPOT_IP=192.168.50.3
      - ROS_DOMAIN_ID=56
      - ROS_DISCOVERY_SERVER=192.168.80.3:21000
      - PAYLOAD_CREDENTIALS=/opt/payload_credentials/payload_guid_and_secret
      - BOSDYN_CLIENT_USERNAME=user
      - BOSDYN_CLIENT_PASSWORD=bbbdddaaaiii
    # Launch the Spot ROS 2 driver 
    command: ros2 launch spot_driver spot_driver_with_namespace.launch.py spot_name:=Eddie config_file:=/spot_ros_params.yml
    # depends_on:
      # - ros_fastdds_discovery_server
